name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker-compose.yml'
      - '.github/workflows/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        run: |
          docker build -t aravindreddy9548/myapp-backend:latest backend/
          docker push aravindreddy9548/myapp-backend:latest

      - name: Build and push frontend
        run: |
          docker build -t aravindreddy9548/myapp-frontend:latest frontend/
          docker push aravindreddy9548/myapp-frontend:latest
