name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Pull and run containers
        run: |
          docker pull aravindreddy9548/myapp-backend:latest
          docker pull aravindreddy9548/myapp-frontend:latest
          docker-compose up -d
