name: Build and Push Full Stack App

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'docker-compose.yml'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        run: |
          docker build -t aravindreddy9548/myapp-backend:latest backend/
          docker push aravindreddy9548/myapp-backend:latest

      - name: Build and push frontend
        run: |
          docker build -t aravindreddy9548/myapp-frontend:latest frontend/
          docker push aravindreddy9548/myapp-frontend:latest
