name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (for React build)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install

    - name: Build frontend (React)
      working-directory: frontend
      run: npm run build

    - name: Copy React build into backend
      run: cp -r frontend/build backend/

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t aravindreddy9548/myapp:latest backend/

    - name: Push Docker image
      run: docker push aravindreddy9548/myapp:latest
